### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by Pablo-CC** [anchore/kubernetes-admission-controller#11]
Trying to deploy following these instructions:
https://anchore.com/admission-control-in-kubernetes-with-anchore/

**This error only happens when using 0.2.1 and 0.20 tags for the image.** 

Install: `helm install --name=democtl -f my_values.yaml .`

<pre>
<b>$ cat my_values.yaml</b>
anchore:
  endpoint: "http://&lt;anchore-engine-IP&gt;:8228"
  credentialsSecret: anchore-credentials
</pre>
<pre>
<b>$ cat values.yaml</b>
# Default values for anchore-admission-controller.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
logVerbosity: 6

image: "anchore/kubernetes-admission-controller:v0.2.1"
imagePullPolicy: IfNotPresent

service:
  name: anchoreadmissioncontroller
  type: ClusterIP
  internalPort: 443
  externalPort: 443

apiService:
  group: admission.anchore.io
  version: v1beta1

credentialsSecret: anchore-credentials
anchoreEndpoint: ""
policySelectors:
  - Selector:
      ResourceType: "image"
      SelectorKeyRegex: ".*"
      SelectorValueRegex: ".*"
    PolicyReference:
      Username: "admin"
      # This is the default bundle id in anchore engine
      PolicyBundleId: "2c53a13c-1765-11e8-82ef-23527761d060"
    # Mode is one of: "policy", "analysis", or "breakglass". policy=>require policy pass, analysis=>require image analyzed, breakglass=>do nothing
    Mode: breakglass

# Request analysis of images if not already analyzed. This is the default if the above two are false, but is ignored if
# strict gating or analysis gating are true
requestAnalysis: true

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#nodeselector
nodeSelector: {}

## Ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
tolerations: []

## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
affinity: {}

</pre>

<pre>
<b>$ kubectl describe pods democtl-anchore-admission-controller-5bb767dc89-z7mjk </b>
Name:               democtl-anchore-admission-controller-5bb767dc89-z7mjk
Namespace:          default
Priority:           0
PriorityClassName:  <none>
Node:               master/192.168.3.17
Start Time:         Mon, 01 Jul 2019 16:44:23 +0100
Labels:             app=anchore-admission-controller
                    pod-template-hash=5bb767dc89
                    release=democtl
Annotations:        cni.projectcalico.org/podIP: 10.42.0.19/32
Status:             Running
IP:                 10.42.0.19
Controlled By:      ReplicaSet/democtl-anchore-admission-controller-5bb767dc89
Containers:
  anchore-admission-controller:
    Container ID:  docker://b4f88d2a5177e8273d7550fecb661af155182d6b74a14fe0fafcf9bea0d15628
    Image:         anchore/kubernetes-admission-controller:v0.2.1
    Image ID:      docker-pullable://anchore/kubernetes-admission-controllerÉsha256:a3fa1917ea6cab2b136858042b9cbfd0037f8dc97fbc7f966cdabab3a78266d0
    Port:          443/TCP
    Host Port:     0/TCP
    Command:
      /anchore-kubernetes-admission-controller
      --audit-log-path=-
      --tls-cert-file=/var/serving-cert/tls.crt
      --tls-private-key-file=/var/serving-cert/tls.key
      --v=6
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Mon, 01 Jul 2019 16:46:00 +0100
      Finished:     Mon, 01 Jul 2019 16:46:00 +0100
    Ready:          False
    Restart Count:  4
    Readiness:      http-get https://:443/healthz delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:
      CONFIG_FILE_PATH:       /config/config.json
      CREDENTIALS_FILE_PATH:  /credentials/credentials.json
    Mounts:
      /config from controller-config (rw)
      /credentials from anchore-auth (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from democtl-anchore-admission-controller-token-844zk (ro)
      /var/serving-cert from serving-cert (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  serving-cert:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  anchore-admission-controller-certs
    Optional:    false
  controller-config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      democtl-controller-config
    Optional:  false
  anchore-auth:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  anchore-credentials
    Optional:    false
  democtl-anchore-admission-controller-token-844zk:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  democtl-anchore-admission-controller-token-844zk
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                   From               Message
  ----     ------     ----                  ----               -------
  Normal   Scheduled  2m29s                 default-scheduler  Successfully assigned default/democtl-anchore-admission-controller-5bb767dc89-z7mjk to master
  Normal   Pulled     53s (x5 over 2m26s)   kubelet, master    Container image "anchore/kubernetes-admission-controller:v0.2.1" already present on machine
  Normal   Created    52s (x5 over 2m26s)   kubelet, master    Created container
  Normal   Started    52s (x5 over 2m25s)   kubelet, master    Started container
  Warning  BackOff    41s (x10 over 2m21s)  kubelet, master    Back-off restarting failed container
</pre>

<pre>
<b>$ kubectl logs democtl-anchore-admission-controller-5bb767dc89-z7mjk </b>
I0701 15:47:29.348121       1 main.go:550Å Initializing configuration
I0701 15:47:29.348203       1 main.go:562Å Loading configuration from /config/config.json
I0701 15:47:29.348546       1 main.go:580Å Loading creds from /credentials/credentials.json
E0701 15:47:29.348566       1 main.go:585Å Could not load auth configuration err=<nil>
panic: runtime error: invalid memory address or nil pointer dereference
Äsignal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x148956aÅ

goroutine 1 ÄrunningÅ:
main.main()
	/go/src/github.com/anchore/kubernetes-admission-controller/cmd/kubernetes-admission-controller/main.go:586 +0xe3a

</pre>

**Comment by zhill** [comment]
@Pablo-CC this is due to missing auth config. I need to clean up the error messaging on that one a bit, but it's trying to load the auth config file and not finding it. Have you confirmed that you nave created a generic secret 'anchore-credentials'? Usually this issue is caused by a missing or malformed secret for the anchore service auth creds.

**Comment by Pablo-CC** [comment]
@zhill I'm afraid I do.
```
$ kubectl describe secrets anchore-credentials 
Name:         anchore-credentials
Namespace:    default
Labels:       <none>
Annotations:  <none>

Type:  Opaque

Data
====
password:  6 bytes
username:  5 bytes
```

**Comment by Pablo-CC** [comment]
Ok I figured it out. The tutorial at https://anchore.com/admission-control-in-kubernetes-with-anchore/ is wrong. You have to create the secret `anchore-credentials` like this so it is mounted properly:

`$ kubectl create secret generic anchore-credentials --from-file=credentials.json`

With the `credentials.json` file looking like this:

```
$ cat credentials.json 
{
  "users": [
    {"username": "admin", "password": "foobar"}
  ]
}
```
