### ISSUE TITLE
[Enhancement] support kube resources other than pods

### ISSUE THREAD

**Issue by pvnovarese** [anchore/kubernetes-admission-controller#18]
Hey there admission control fans,

currently we are only validating pods.  

We would like to be able to validate other workload resources (specifically, deployments, but in general statefulsets, etc).  

The immediate concern is a case where:
1) deployment is created 
2) new vulnerability is disclosed and definitions are updated which would cause an image that was passing to now fail
3) try to create additional pods (either for scaling up or for rescheduling etc) which is blocked because the image is now failing evaluation.  

For my own personal edification the only thing I am immediately interested in is deployments but we could potentially validate pods, deployments, replicasets, replicationcontrollers, statefulsets, daemonsets, jobs, cronjobs

**Comment by zhill** [comment]
Yes, any workload with a pod spec should be able to be supported fairly easily.

To achieve those steps, you actually want to remove validation on pods and only validate a specific other resource.

**Comment by zhill** [comment]
Primary change will be to generalize: https://github.com/anchore/kubernetes-admission-controller/blob/master/cmd/kubernetes-admission-controller/main.go#L174

That section can expand to support more kinds and then have the lookup logic to extract the pod specs and pass them downstream into the same processing logic.

The set of kinds supported in the code should be broad. The actual determination of what kinds should be sent to the webhook for validation is configured in the validatingwebhookconfiguration resource, so is user-configurable in cluster as long as the controller itself can properly parse and handle the workload resources.
