### ISSUE TITLE
Question: Use `ko` to build images?

### ISSUE THREAD

**Issue by imjasonh** [anchore/kubernetes-admission-controller#49]
The [`Dockerfile` used to build the admission controller](https://github.com/anchore/kubernetes-admission-controller/blob/master/Dockerfile) container is pretty out of date. It builds using `golang:1.13-alpine` which was released 3 years ago and has not been officially supported since 1.15 was released a year later. The image it builds is based on `alpine:3.10`, also released 3 years ago, and [EOLed 16 months ago](https://endoflife.date/alpine).

Aside from these things, which could be addressed just by updating these references, the build doesn't do a lot that requires a `Dockerfile` in the first place. The build process is to `go build ./cmd/kubernetes-admission-controller` and move that into an image based on `alpine`, with ca-certs included.

This is exactly the case that [`ko`](https://ko.build) was designed to solve, and it's exactly what `ko` is optimized for. Instead of `docker build`, you could `ko build` and get a smaller, more minimal image, which builds faster due to sharing your build cache, and `ko` will generate and push an SBOM for your application as well. [Kyverno](https://github.com/kyverno/kyverno/issues/2925) recently migrated to `ko`, and your build process looks even simpler than theirs.

Would you accept a PR to update your build process to use `ko` instead, and remove your outdated Dockerfile?

It looks like we'd also need to update the [Helm chart](https://github.com/anchore/anchore-charts/blob/b1f6236c90d67258e413415c36effba17d535079/stable/anchore-admission-controller/values.yaml#L8) to use the newly built image, which we should reference by digest instead of by mutable tags.

It looks like you're using Skaffold for local development, and [Skaffold also has support for building images with `ko`](https://skaffold.dev/docs/pipeline-stages/builders/ko/), so we could update that as well.

Let me know if you're interested, and I can start making some exploratory changes.

**Comment by luhring** [comment]
I'm not a decision maker, but I think this is a **fantastic** idea, FWIW 😍 

cc: @zhill

**Comment by zhill** [comment]
Hi @imjasonh ! We're evaluating base image options as some users have preferences/requirements for the images they use, so still in requirements gathering phase. But, if we decide to stay on alpine, ko is an option and looks compelling from what I've seen so far.

**Comment by imjasonh** [comment]
> Hi @imjasonh ! We're evaluating base image options as some users have preferences/requirements for the images they use, so still in requirements gathering phase. But, if we decide to stay on alpine, ko is an option and looks compelling from what I've seen so far.

Good to hear!

For what it's worth, the decision to use `ko` can be considered separately from deciding what base image to use, since `ko` lets you [configure your base image](https://ko.build/configuration/#overriding-base-images).

If you decide that you want to add more steps to your Dockerfile, e.g., adding more packages from the base image's package manager, then `ko` may not be a good fit. But if you decide to stick with the current approach of putting a Go binary directly on top of your base image, it may be a good fit, and you'd get SBOMs, faster builds, and more to boot.

**Comment by zhill** [comment]
Great to know! I've only just started looking at the ko docs in more depth.

**Comment by zhill** [comment]
@imjasonh I've opened #57 with an initial ko implementation to see how it goes. I'd appreciated any suggestions/improvements you can offer there. I need to get a release out so I can't wait long on that PR specifically but we can iterate after it merges as well if you see any specific things that can be improved.

**Comment by zhill** [comment]
Added ko support in #57, closing this. Thanks @imjasonh and @luhring
